version: "3"
services:
  web:
    build: .
    env_file:
      - .env
    entrypoint:
      - /entrypoint.sh
      - /init_db.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000